// All site copy lives here. Public pages use `useT()` from `@/lib/i18n` and
// pick from `dict[lang]`. Server code and admin/portal pages still import the
// NL-only `t` shortcut.
export const nl = {
  brand: { name: "Yeketi Motorworks", tagline: "unity in craftsmanship" },
  nav: {
    home: "Home",
    diensten: "Diensten",
    restauratie: "Restauratie",
    recent: "Recent werk",
    over: "Over ons",
    offerte: "Offerte",
    portal: "Klantenportaal",
    aria: "Hoofdnavigatie",
    menuOpen: "Menu openen",
    menuClose: "Menu sluiten",
  },
  hero: {
    eyebrow: "Klassiekers — restauratie & plaatwerk",
    headline: "Vakmanschap dat verdwijnt, leeft hier verder.",
    subline:
      "Restauratie van klassiekers door meester-ambachtslieden — persoonlijk begeleid van inspectie tot aflevering.",
    ctaQuote: "Vraag een offerte",
    ctaFollow: "Volg een restauratie",
    imageCaption: "Werkplaats — Erbil",
    imageAlt: "Gerestaureerde VW T2 onderweg na aflevering",
  },
  story: {
    eyebrow: "Het verhaal",
    title: "Een ambacht dat een tweede thuis vond.",
    body: [
      "Yeketi begon met één eenvoudige vaststelling: de klassiekers die wij in Europa koesteren, worden steeds zeldzamer hersteld. Niet door gebrek aan liefde, maar door gebrek aan tijd, aan handen, aan ruimte in de werkplaats.",
      "In de bergen van Koerdistan, in Iraq, werken nog steeds meester-ambachtslieden die het métier in de vingers hebben. Plaatwerkers, lassers, schilders — opgeleid in een traditie waar elke deuk met de hand wordt uitgeklopt. Wij brengen Europese auto's naar hen toe, en de auto die terugkomt is meer dan hersteld. Hij is opnieuw verteld.",
    ],
    pullQuote:
      "Een auto bewaart de adem van de mensen die hem maken. Daarom kiezen wij onze handen met zorg.",
    pullAttribution: "— Baram Maro, oprichter",
  },
  process: {
    eyebrow: "Hoe het werkt",
    title: "Vijf stappen, één aanspreekpunt.",
    steps: [
      { n: "01", t: "Inspectie aan huis", d: "Wij komen langs, maken foto's, bespreken uw wensen en de staat van de wagen." },
      { n: "02", t: "Offerte & planning", d: "Een transparante offerte met afgebakende posten en een realistische tijdslijn." },
      { n: "03", t: "Transport", d: "Transport persoonlijk verzorgd — Baram brengt de wagen zelf naar de werkplaats en blijft ter plaatse tijdens de restauratie." },
      { n: "04", t: "Restauratie met foto-updates", d: "Iedere week beelden vanuit de werkplaats. U volgt elke fase mee, op uw eigen tempo." },
      { n: "05", t: "Aflevering", d: "De wagen komt terug, gepoetst en gekeurd, klaar voor de weg of voor de etalage." },
    ],
  },
  why: {
    eyebrow: "Waarom Yeketi",
    title: "Vier redenen die het verschil maken.",
    items: [
      {
        t: "Eerlijke prijs",
        d: "Vakwerk van een niveau dat hier zeldzaam is geworden — aan een prijs die scherper ligt dan een restauratie in België, zonder in te boeten op kwaliteit.",
      },
      {
        t: "Kortere doorlooptijd",
        d: "Wij denken in weken en maanden, niet in jaren. De werkplaats werkt met meerdere ambachtslieden op één project.",
      },
      {
        t: "Traditioneel vakwerk",
        d: "Plaatstaal wordt bij ons autogeen gelast — met gas- en zuurstofvlam, zoals het hoort bij een oldtimer. Een techniek die in Europa bijna verdwenen is, maar de juiste blijft: de las loopt mee met het staal, geeft minder spanning op het paneel en houdt generaties mee.",
      },
      {
        t: "Persoonlijke begeleiding",
        d: "Eén aanspreekpunt, van eerste foto tot aflevering. Updates met beelden, in uw taal, op uw tempo.",
      },
    ],
    proof: {
      eyebrow: "Het bewijs",
      body: "Geen MIG, geen kortere weg: een vlam, een staaf, en een hand die rustig blijft. Zo werd plaatstaal van een oldtimer ooit aan elkaar gezet — en zo doen wij het nog steeds.",
    },
    weldingVideo: {
      caption: "Autogeen-lassen in de werkplaats — gas- en zuurstofvlam op klassiek plaatstaal.",
      aria: "Korte video van autogeen-lassen op plaatstaal in de werkplaats",
    },
  },
  recent: {
    eyebrow: "Recente restauratie",
    title: "Een VW T2, herboren.",
    body: "Eén maand werk: plaatwerkrestauratie en exterieur in originele kleurstelling. Lees het volledige verhaal.",
    cta: "Bekijk de restauratie",
    href: "/recent-werk",
  },
  footer: {
    columnsTitle: "Yeketi Motorworks",
    tagline: "unity in craftsmanship",
    contact: "Vredeplein 23, 3010 Kessel-Lo (BE)",
    email: "info@yeketimotorworks.com",
    instagram: "Instagram",
    rights: "© 2026 Yeketi Motorworks",
    kvk: "BTW BE 0694.858.510",
    contactTitle: "Contact",
    companyTitle: "Bedrijf",
    links: {
      diensten: "Diensten",
      over: "Over ons",
      offerte: "Offerte",
      portal: "Klantenportaal",
      privacy: "Privacy & cookies",
    },
  },
  diensten: {
    eyebrow: "Diensten",
    title: "Twee paden. Hetzelfde vakmanschap.",
    intro: "Of u nu een specifiek paneel wilt laten herstellen of een volledige restauratie wenst — wij vertrekken altijd van een gesprek en een eerlijke inschatting.",
    tiers: [
      {
        t: "Plaatwerk & carrosserie",
        sub: "Voor wie één element wil herstellen.",
        items: [
          "Uitdeuken met de hand, geen plamuur waar het niet hoort",
          "Lassen en vernieuwen van rotte panelen — autogeen gelast met de hand, de juiste techniek voor klassiek plaatstaal",
          "Voorbereiding voor spuitwerk, of volledige aflakking",
          "Chroomwerk en sierlijsten in originele staat",
        ],
        cta: "Vraag een offerte",
      },
      {
        t: "Volledige restauratie",
        sub: "Voor wie de wagen terug wil zoals hij ooit was.",
        items: [
          "Demontage tot op het naakte chassis",
          "Behandeling tegen corrosie, zinkprimer, nieuwe lak",
          "Mechaniek, elektriciteit en interieur in originele specificaties",
          "Eindkeuring, poetsbeurt, transport tot voor uw deur",
        ],
        cta: "Plan een gesprek",
      },
    ],
    faqTitle: "Veelgestelde vragen",
    welding: {
      eyebrow: "Techniek",
      title: "Autogeen gelast, zoals het hoort.",
      body: "Klassiek plaatstaal vraagt om een vlamlas, niet om een snelle MIG-puls. Onze plaatwerkers lassen de panelen autogeen — een ambacht dat in Europa bijna verdwenen is, maar de juiste techniek blijft voor een oldtimer: minder spanning op het paneel, een gladdere overgang en een verbinding die generaties meegaat.",
      videoCaption: "Autogeen-lassen op plaatstaal — met gas- en zuurstofvlam, met de hand.",
      videoAria: "Korte video van autogeen-lassen in de werkplaats",
    },
    faq: [
      { q: "Hoe verloopt het transport en de verzekering?", a: "Baram verzorgt het transport voorlopig persoonlijk: hij brengt de wagen zelf naar de werkplaats, blijft ter plaatse tijdens het werk, en regelt vooraf de gepaste verzekering op de afgesproken waarde. Alle documenten krijgt u ter inzage voor de wagen vertrekt." },
      { q: "Wat is een realistische doorlooptijd?", a: "Plaatwerk: enkele weken tot twee maanden. Een volledige restauratie duurt doorgaans rond drie maanden — wij werken parallel met meerdere ambachtslieden in gespecialiseerde werkplaatsen, in plaats van fase na fase." },
      { q: "Hoe houden jullie mij op de hoogte?", a: "U krijgt wekelijks foto's en, op vraag, een korte videoboodschap uit de werkplaats. Eén aanspreekpunt in België voor al uw vragen." },
      { q: "Kan ik in schijven betalen?", a: "Ja. Wij werken standaard met drie schijven: bij start, halverwege en bij aflevering. Schijven zijn gekoppeld aan vooraf afgesproken mijlpalen." },
      { q: "Welke garantie geven jullie op het werk?", a: "Twee jaar garantie op plaatwerk en lakwerk, één jaar op mechanische ingrepen. Wij blijven aanspreekbaar, ook na aflevering." },
    ],
  },
  caseT2: {
    eyebrow: "Onze werkwijze",
    title: "Restauratie — van aankomst tot aflevering.",
    lead: "Een volledige restauratie loopt bij ons parallel: plaatwerk, mechaniek, lakwerk en interieur lopen tegelijk in gespecialiseerde werkplaatsen, elk met de juiste meester aan het werk. Daardoor staat een klassieker bij ons rond drie maanden in de werkplaats — niet de jaren die hetzelfde werk elders zou kosten.",
    chapters: [
      { date: "Fase 01", t: "Aankomst & inspectie", d: "De wagen arriveert in de werkplaats. Een nauwgezette inspectie van carrosserie, chassis en mechaniek; alle aandachtspunten worden gefotografeerd en met de eigenaar besproken voor er één bout wordt losgedraaid." },
      { date: "Fase 02", t: "Plaatwerk", d: "Rotte panelen worden vakkundig uitgesneden en met de hand opnieuw gevormd uit nieuw staal, volgens de originele profielen. De nieuwe stukken worden autogeen ingelast — met gas- en zuurstofvlam, de traditionele techniek voor klassiek plaatstaal die in Europa bijna verdwenen is. De las loopt mee met het staal, geeft minder spanning op het paneel en houdt generaties mee. Geen plamuur waar het niet hoort — elke deuk wordt geklopt zoals het hoort bij een klassieker." },
      { date: "Fase 03", t: "Mechaniek", d: "Het motorblok wordt volledig gereviseerd. Pakkingen, zuigers en kleppen worden vernieuwd; originele onderdelen worden waar mogelijk gerestaureerd in plaats van vervangen, om het karakter van de wagen te behouden." },
      { date: "Fase 04", t: "Lakwerk", d: "Meerdere lagen primer, plamuur en lak — exact volgens de originele kleurcode van de fabrikant. Met de hand gepolijst tot de oorspronkelijke diepte en glans terug zichtbaar zijn." },
      { date: "Fase 05", t: "Interieur", d: "Nieuwe binnenbekleding op maat in originele stof en kleur. Stuur, pedalen en schakelpook blijven het origineel — alles wat de eigenaar dagelijks aanraakt, draagt de patina van een halve eeuw geschiedenis." },
      { date: "Fase 06", t: "Aflevering", d: "Eindcontrole en transport tot voor de deur. De wagen rijdt opnieuw zijn eerste kilometers — een klassieker die nog generaties mee kan." },
    ],
    closing:
      "Restauratie is geen poging om de tijd terug te draaien. Het is een belofte dat het verhaal verder mag gaan.",
    cta: "Start uw restauratie",
    weldingVideoCaption: "Autogeen-lassen — de traditionele techniek voor klassiek plaatstaal.",
    weldingVideoAria: "Korte video van autogeen-lassen op plaatstaal",
  },
  over: {
    eyebrow: "Over Yeketi",
    title: "Yeketi betekent eenheid. Eenheid in vakmanschap.",
    body: [
      "Yeketi is een Koerdisch woord voor eenheid. Het kiezen van die naam was geen marketingbeslissing — het was een principe. Wij brengen twee werelden samen: Europese eigenaars die hun klassieker willen koesteren, en een netwerk van Koerdische meester-ambachtslieden die het oude métier nog in de vingers hebben.",
      "De werkplaats ligt in de buurt van Erbil, in de Koerdistan-regio van Iraq. Het is een rustige plek, ver van de massaproductie, waar men nog tijd neemt om naar metaal te luisteren. De ambachtslieden — sommigen al dertig jaar in het vak — werken met de geduldige nauwkeurigheid die deze auto's verdienen.",
      "Vanuit België coördineren wij elk project persoonlijk. Wij komen langs voor de inspectie, regelen het transport, en zijn uw enige aanspreekpunt zolang de wagen weg is. U hoort van ons in het Nederlands. U krijgt foto's per week, en een eerlijk antwoord wanneer u erom vraagt.",
    ],
    founderName: "Baram Maro — oprichter",
    founderQuote:
      "Ik wil dat mijn klanten hun wagen op een dag aan hun kleinkinderen kunnen doorgeven. Dat is de enige reden dat dit bestaat.",
  },
  offerte: {
    eyebrow: "Offerte aanvragen",
    title: "Vertel ons over uw klassieker.",
    intro: "Geen verplichting, geen verkoopstruc. U krijgt binnen twee werkdagen een persoonlijke reactie van Baram.",
    labels: {
      naam: "Naam",
      email: "E-mail",
      telefoon: "Telefoon",
      merk: "Merk",
      model: "Model",
      bouwjaar: "Bouwjaar",
      type: "Type werk",
      typePlaat: "Plaatwerk",
      typeFull: "Volledige restauratie",
      typeAdvies: "Advies",
      beschrijving: "Beschrijving",
      fotos: "Foto's (max. 5)",
      submit: "Verstuur aanvraag",
      sending: "Versturen…",
    },
    success: {
      title: "Bedankt voor uw aanvraag.",
      body: "Wij hebben uw bericht goed ontvangen. Baram neemt binnen twee werkdagen persoonlijk contact op.",
    },
    error: "Er ging iets mis bij het versturen. Probeer het opnieuw via het formulier.",
    photoTooMany: "Maximaal vijf foto's.",
    back: "Terug naar home",
    descriptionPlaceholder: "Wat wenst u te laten doen? Eventuele zorgpunten of bijzonderheden…",
    photosOptional: "Optioneel — helpt ons een snellere inschatting te maken.",
    photosChosen: (n: number) => (n === 1 ? "1 foto toegevoegd" : `${n} foto's toegevoegd`),
    onlyImages: "Alleen afbeeldingen toegestaan.",
    photoTooLarge: "Een foto is groter dan 8MB.",
    checkFields: "Controleer de ingevulde gegevens.",
    addPhotos: "Foto's toevoegen",
    addPhotosHint: "Klik of sleep tot 5 foto's hierheen (JPG, PNG · max. 8MB per foto)",
    removePhoto: "Verwijder foto",
  },
  login: {
    title: "Klantenportaal",
    body: "Het beveiligde portaal voor lopende restauraties opent binnenkort. U ontvangt uw inloggegevens per e-mail zodra uw project van start gaat.",
    back: "Terug naar home",
  },
  portal: {
    loginTitle: "Klantenportaal",
    loginSubline: "Log in met je e-mailadres en wachtwoord.",
    emailLabel: "E-mailadres",
    emailPlaceholder: "naam@voorbeeld.be",
    passwordLabel: "Wachtwoord",
    passwordPlaceholder: "Je wachtwoord",
    send: "Inloggen",
    sending: "Bezig…",
    forgot: "Wachtwoord vergeten?",
    resetTitle: "Wachtwoord opnieuw instellen",
    resetSubline: "Vul je e-mailadres in en we sturen je een link om een nieuw wachtwoord te kiezen.",
    resetSend: "Stuur resetlink",
    resetSent: "Check je inbox — als het adres bij ons bekend is, ontvang je een e-mail met een resetlink.",
    backToLogin: "Terug naar inloggen",
    newPasswordTitle: "Kies een nieuw wachtwoord",
    newPasswordLabel: "Nieuw wachtwoord",
    newPasswordSave: "Wachtwoord opslaan",
    newPasswordSaved: "Wachtwoord opgeslagen. Je wordt doorgestuurd…",
    resetLinkExpired: "Deze resetlink is verlopen. Vraag even een nieuwe link aan om je wachtwoord te kiezen.",
    resetLinkInvalid: "Deze resetlink is niet meer geldig. Vraag even een nieuwe link aan om je wachtwoord te kiezen.",
    requestNewResetLink: "Nieuwe resetlink aanvragen",
    passwordTooShort: "Wachtwoord moet minstens 8 tekens bevatten.",
    invalidCredentials: "E-mailadres of wachtwoord klopt niet.",
    invalidEmail: "Vul een geldig e-mailadres in.",
    sendError: "Er ging iets mis. Probeer het opnieuw via het formulier.",
    rateLimited: "Je hebt net al een link opgevraagd. Controleer je mailbox of probeer over een paar minuten opnieuw.",
    loginRateLimited: "Te veel inlogpogingen. Wacht een paar minuten en probeer opnieuw, of gebruik 'Wachtwoord vergeten?'.",
    emailNotConfirmed: "Je e-mailadres is nog niet bevestigd. Check je inbox voor de bevestigingsmail.",
    networkError: "Geen verbinding met de server. Check je internet en probeer opnieuw.",
    loginUnknownError: "Inloggen lukte niet. Probeer opnieuw of klik op 'Wachtwoord vergeten?'.",
    showPassword: "Toon wachtwoord",
    hidePassword: "Verberg wachtwoord",
    showShort: "Toon",
    hideShort: "Verberg",
    inviteWelcomeTitle: "Welkom — stel je wachtwoord in",
    inviteWelcomeBody: "Kies een wachtwoord om je toegang tot het klantenportaal te activeren.",
    settingPasswordFor: "Je stelt een wachtwoord in voor",
    verifyingLink: "Recovery-link wordt geverifieerd…",
    linkExpiredAfterWait: "We konden je link niet verifiëren. Vraag een nieuwe link aan om verder te gaan.",
    notRegistered:
      "Dit e-mailadres staat nog niet in ons systeem. Neem contact op met Baram zodat we je restauratie kunnen klaarzetten.",
    overviewTitle: "Jouw restauraties",
    overviewIntro: "Volg de voortgang van je project, fase per fase.",
    empty: "Je restauratie wordt klaargezet — je ontvangt een e-mail zodra de eerste update er is.",
    backToOverview: "Terug naar overzicht",
    logout: "Uitloggen",
    welcome: "Welkom terug",
    timelineTitle: "Tijdlijn",
    noUpdates: "Nog niet gestart.",
    statusLabels: {
      intake: "Intake",
      transport_out: "Onderweg naar werkplaats",
      in_workshop: "In de werkplaats",
      transport_return: "Onderweg terug",
      delivered: "Afgeleverd",
      archived: "Gearchiveerd",
    },
  },
  recentWerk: {
    eyebrow: "Recente restauratie",
    title: "Recent werk.",
    intro: "Elke restauratie krijgt hier zijn eigen verhaal. We beginnen bij het allereerste project — en bouwen verder, oldtimer per oldtimer.",
    projectLabel: "Project 01 · 2024",
    projectTitle: "VW T2 Westfalia — van schuurvondst tot bergpas.",
    projectBody:
      "Een originele Westfalia camper, binnengebracht met sporen van jarenlang stilstaan. Focus lag op plaatwerk, slaapdak en exterieur — techniek en interieur bleven in deze fase buiten beschouwing. Hieronder de chronologie, van eerste inspectie tot eerste rit door de bergen.",
    monthMay: "Mei 2024",
    monthJun: "Juni 2024",
    shots: {
      aankomst: { alt: "VW T2 Westfalia bij aankomst, achterklep open", caption: "Aankomst — Baram en de eigenaar overlopen de staat van de bus." },
      inventaris: { alt: "VW T2 Westfalia vooraanzicht in tweekleurige originele lak", caption: "Inventaris — alle originele delen blijven behouden waar het kan." },
      slaapdak: { alt: "VW T2 Westfalia zijaanzicht met opgeklapt slaapdak", caption: "Slaapdak opgemeten, kap en scharnieren grondig nagekeken." },
      ontmanteling: { alt: "VW T2 ontdaan van rubbers en ramen, klaar voor schuurwerk", caption: "Ontmanteling — rubbers, ramen en sierlijsten gaan eruit voor het plaatwerk." },
      plamuur: { alt: "VW T2 in plamuur, gemaskeerd voor spuitwerk", caption: "Plamuur en schuurwerk — laag per laag tot het oppervlak weer strak is." },
      eindcontrole: { alt: "Baram Maro en klant bij de afgewerkte VW T2 Westfalia", caption: "Eindcontrole — Baram tekent pas af als élk detail klopt." },
      onderweg: { alt: "Gerestaureerde VW T2 Westfalia in een bergachtig landschap", caption: "Onderweg — de bus rijdt weer waar hij thuishoort." },
    },
    comingSoonLabel: "Project 02 · binnenkort",
    comingSoonBody:
      "De volgende klassieker staat al in de werkplaats. Foto's en verhaal volgen zodra het werk vordert.",
  },
  privacy: {
    eyebrow: "Juridisch",
    title: "Privacy & cookies",
    lastUpdate:
      "Laatste update: juni 2026. Deze verklaring is een plaatsing — definitieve juridische tekst wordt toegevoegd na controle door Nomadix BV.",
    sections: {
      responsibleTitle: "Verantwoordelijke",
      responsibleAddr: "Vredeplein 23, 3010 Kessel-Lo, België",
      responsibleVat: "BTW BE 0694.858.510",
      contactLabel: "Contact:",
      dataTitle: "Welke gegevens verzamelen wij",
      dataItems: [
        "Contactgegevens die je zelf invult via het offerteformulier (naam, e-mail, telefoon).",
        "Voertuiggegevens en foto's die je ons toestuurt voor een inschatting of restauratie.",
        "Inloggegevens van het klantenportaal (e-mailadres voor magic-link login).",
      ],
      useTitle: "Waarvoor gebruiken wij ze",
      useBody:
        "Uitsluitend om je offerteaanvraag te beantwoorden, je restauratie voor te bereiden en uit te voeren, en om je via het portaal en e-mail op de hoogte te houden van de voortgang.",
      cookiesTitle: "Cookies",
      cookiesBody:
        "Wij gebruiken alleen functionele cookies die noodzakelijk zijn voor het inloggen op het klantenportaal. Geen tracking, geen advertentiecookies, geen analytics van derden.",
      retentionTitle: "Bewaartermijn",
      retentionBody:
        "Offerteaanvragen worden 24 maanden bewaard. Project- en restauratiedossiers worden zolang bewaard als de wettelijke administratieplicht vereist (7 jaar).",
      rightsTitle: "Jouw rechten",
      rightsBefore: "Je hebt recht op inzage, correctie en verwijdering van je gegevens. Stuur een e-mail naar ",
      rightsAfter: " en we reageren binnen 30 dagen.",
    },
    back: "Terug naar home",
  },
  notFound: {
    eyebrow: "404",
    title: "Deze weg loopt dood — maar elke klassieker verdient een tweede kans.",
    body: "De pagina die je zocht bestaat niet (meer). Keer terug naar de werkplaats.",
    cta: "Terug naar home",
  },
  weldingVideo: {
    defaultAria: "Autogeen-lassen in de werkplaats",
    play: "Speel de video — autogeen-lassen",
  },
  contact: {
    eyebrow: "Contact",
    title: "Stuur een bericht",
    intro: "Een vraag, een idee, of gewoon zin om eens te praten over een klassieker? Schrijf een bericht. Baram antwoordt persoonlijk.",
    langLabel: "Taal · antwoord per mail",
    langNl: "Nederlands",
    langEn: "Engels",
    nameLabel: "Naam",
    emailLabel: "E-mail",
    messageLabel: "Bericht",
    submit: "Verstuur bericht",
    sending: "Versturen…",
    successTitle: "Bedankt — je bericht is binnen.",
    successBody: "We sturen je ook een uitnodiging voor het portaal, zodat je het antwoord en alle vervolgberichten op één plek terugvindt.",
    back: "Terug naar de site",
    error: "Er ging iets mis bij het versturen. Probeer het opnieuw via het formulier.",
  },
};

export type Copy = typeof nl;

export const en: Copy = {
  brand: { name: "Yeketi Motorworks", tagline: "unity in craftsmanship" },
  nav: {
    home: "Home",
    diensten: "Services",
    restauratie: "Restoration",
    recent: "Recent work",
    over: "About",
    offerte: "Quote",
    portal: "Client portal",
    aria: "Main navigation",
    menuOpen: "Open menu",
    menuClose: "Close menu",
  },
  hero: {
    eyebrow: "Classics — restoration & bodywork",
    headline: "Craftsmanship that's disappearing, lives on here.",
    subline:
      "Restoration of classic cars by master craftsmen — personally guided from inspection to delivery.",
    ctaQuote: "Request a quote",
    ctaFollow: "Follow a restoration",
    imageCaption: "Workshop — Erbil",
    imageAlt: "Restored VW T2 on the road after delivery",
  },
  story: {
    eyebrow: "The story",
    title: "A craft that found a second home.",
    body: [
      "Yeketi began with one simple observation: the classic cars we cherish in Europe are restored less and less. Not for lack of love, but for lack of time, of hands, of room in the workshop.",
      "In the mountains of Kurdistan, in Iraq, master craftsmen still work who carry the trade in their fingers. Panel beaters, welders, painters — trained in a tradition where every dent is tapped out by hand. We bring European cars to them, and the car that comes back is more than restored. It is retold.",
    ],
    pullQuote:
      "A car carries the breath of the people who built it. That is why we choose our hands with care.",
    pullAttribution: "— Baram Maro, founder",
  },
  process: {
    eyebrow: "How it works",
    title: "Five steps, one point of contact.",
    steps: [
      { n: "01", t: "On-site inspection", d: "We come to you, take photos, and discuss your wishes and the state of the car." },
      { n: "02", t: "Quote & planning", d: "A transparent quote with itemised work and a realistic timeline." },
      { n: "03", t: "Transport", d: "Transport handled personally — Baram drives the car to the workshop himself and stays on-site for the duration of the restoration." },
      { n: "04", t: "Restoration with photo updates", d: "Weekly images from the workshop. You follow every stage at your own pace." },
      { n: "05", t: "Delivery", d: "The car returns, detailed and inspected, ready for the road or the showroom." },
    ],
  },
  why: {
    eyebrow: "Why Yeketi",
    title: "Four reasons that make the difference.",
    items: [
      { t: "Fair price", d: "Craftsmanship of a level that has become rare here — at a price that sits sharper than a restoration in Belgium, without compromising on quality." },
      { t: "Shorter lead time", d: "We think in weeks and months, not years. The workshop puts several craftsmen on one project." },
      { t: "Traditional craft", d: "Sheet metal is gas-welded by hand — with oxy-acetylene flame, the way a classic should be welded. A technique nearly lost in Europe, but still the right one: the weld moves with the steel, leaves less stress in the panel and lasts for generations." },
      { t: "Personal guidance", d: "One point of contact, from the first photo to delivery. Updates with images, in your language, at your pace." },
    ],
    proof: {
      eyebrow: "The proof",
      body: "No MIG, no shortcut: a flame, a rod, and a hand that stays steady. That is how a classic's sheet metal was once put together — and how we still do it.",
    },
    weldingVideo: {
      caption: "Gas-welding in the workshop — oxy-acetylene flame on classic sheet metal.",
      aria: "Short video of gas-welding sheet metal in the workshop",
    },
  },
  recent: {
    eyebrow: "Recent restoration",
    title: "A VW T2, reborn.",
    body: "One month of work: bodywork restoration and exterior in the original colour scheme. Read the full story.",
    cta: "View the restoration",
    href: "/recent-werk",
  },
  footer: {
    columnsTitle: "Yeketi Motorworks",
    tagline: "unity in craftsmanship",
    contact: "Vredeplein 23, 3010 Kessel-Lo (BE)",
    email: "info@yeketimotorworks.com",
    instagram: "Instagram",
    rights: "© 2026 Yeketi Motorworks",
    kvk: "VAT BE 0694.858.510",
    contactTitle: "Contact",
    companyTitle: "Company",
    links: {
      diensten: "Services",
      over: "About",
      offerte: "Quote",
      portal: "Client portal",
      privacy: "Privacy & cookies",
    },
  },
  diensten: {
    eyebrow: "Services",
    title: "Two paths. The same craftsmanship.",
    intro: "Whether you want a single panel repaired or a full restoration — we always start with a conversation and an honest assessment.",
    tiers: [
      {
        t: "Bodywork & panel beating",
        sub: "For those who want one element restored.",
        items: [
          "Hand-tapped dent removal, no filler where it doesn't belong",
          "Welding and replacing rusted panels — gas-welded by hand, the right technique for classic sheet metal",
          "Prep work for painting, or full respray",
          "Chrome and trim restored to original condition",
        ],
        cta: "Request a quote",
      },
      {
        t: "Full restoration",
        sub: "For those who want the car back the way it once was.",
        items: [
          "Disassembly down to the bare chassis",
          "Corrosion treatment, zinc primer, new paint",
          "Mechanics, electrics and interior to original specification",
          "Final inspection, detailing, transport to your door",
        ],
        cta: "Schedule a call",
      },
    ],
    faqTitle: "Frequently asked questions",
    welding: {
      eyebrow: "Technique",
      title: "Gas-welded, the way it should be.",
      body: "Classic sheet metal calls for a flame weld, not a quick MIG pulse. Our panel beaters gas-weld every joint — a craft nearly lost in Europe, but still the right technique for a classic: less stress on the panel, a smoother transition, and a joint that lasts for generations.",
      videoCaption: "Gas-welding sheet metal — oxy-acetylene flame, by hand.",
      videoAria: "Short video of gas-welding in the workshop",
    },
    faq: [
      { q: "How do transport and insurance work?", a: "For now Baram handles transport personally: he drives the car to the workshop himself, stays on-site while the work is under way, and arranges the right insurance at the agreed value beforehand. You receive all documents before the car leaves." },
      { q: "What is a realistic lead time?", a: "Bodywork: a few weeks to two months. A full restoration typically takes around three months — we work in parallel with multiple craftsmen in specialised workshops, rather than phase after phase." },
      { q: "How do you keep me informed?", a: "You get weekly photos and, on request, a short video message from the workshop. One point of contact in Belgium for all your questions." },
      { q: "Can I pay in instalments?", a: "Yes. We work in three instalments by default: at start, halfway, and on delivery. Instalments are tied to pre-agreed milestones." },
      { q: "What warranty do you offer?", a: "Two years on bodywork and paintwork, one year on mechanical work. We remain available, also after delivery." },
    ],
  },
  caseT2: {
    eyebrow: "Our way of working",
    title: "Restoration — from arrival to delivery.",
    lead: "A full restoration runs in parallel with us: bodywork, mechanics, paint and interior all happen at the same time in specialised workshops, each with the right master at work. That is why a classic stays with us for around three months — not the years the same work would take elsewhere.",
    chapters: [
      { date: "Stage 01", t: "Arrival & inspection", d: "The car arrives at the workshop. A thorough inspection of body, chassis and mechanics; every point of attention is photographed and discussed with the owner before a single bolt is loosened." },
      { date: "Stage 02", t: "Bodywork", d: "Rusted panels are cut out and reshaped by hand from new steel, true to the original profiles. The new sections are gas-welded in — with oxy-acetylene flame, the traditional technique for classic sheet metal that has nearly disappeared in Europe. The weld moves with the steel, leaves less stress in the panel and lasts for generations. No filler where it doesn't belong — every dent tapped out the way a classic deserves." },
      { date: "Stage 03", t: "Mechanics", d: "The engine block is fully rebuilt. Gaskets, pistons and valves are renewed; original parts are restored rather than replaced wherever possible, to preserve the character of the car." },
      { date: "Stage 04", t: "Paintwork", d: "Multiple layers of primer, filler and paint — exactly to the manufacturer's original colour code. Hand-polished until the original depth and gloss are visible again." },
      { date: "Stage 05", t: "Interior", d: "New upholstery made to measure in original fabric and colour. Steering wheel, pedals and gear lever stay original — everything the owner touches daily carries the patina of half a century of history." },
      { date: "Stage 06", t: "Delivery", d: "Final inspection and transport to your door. The car drives its first kilometres again — a classic ready for generations to come." },
    ],
    closing:
      "Restoration is not an attempt to turn back time. It is a promise that the story may continue.",
    cta: "Start your restoration",
    weldingVideoCaption: "Gas-welding — the traditional technique for classic sheet metal.",
    weldingVideoAria: "Short video of gas-welding sheet metal",
  },
  over: {
    eyebrow: "About Yeketi",
    title: "Yeketi means unity. Unity in craftsmanship.",
    body: [
      "Yeketi is a Kurdish word for unity. Choosing that name was not a marketing decision — it was a principle. We bring two worlds together: European owners who want to cherish their classic car, and a network of Kurdish master craftsmen who still carry the old trade in their hands.",
      "The workshop is located near Erbil, in the Kurdistan region of Iraq. It is a quiet place, far from mass production, where people still take the time to listen to metal. The craftsmen — some with thirty years in the trade — work with the patient precision these cars deserve.",
      "From Belgium we coordinate every project personally. We come by for the inspection, arrange transport, and are your only point of contact while the car is away. You hear from us in English or Dutch. You get photos every week, and an honest answer when you ask for one.",
    ],
    founderName: "Baram Maro — founder",
    founderQuote:
      "I want my clients to be able to hand their car down to their grandchildren one day. That is the only reason this exists.",
  },
  offerte: {
    eyebrow: "Request a quote",
    title: "Tell us about your classic.",
    intro: "No obligation, no sales pitch. You'll get a personal response from Baram within two working days.",
    labels: {
      naam: "Name",
      email: "Email",
      telefoon: "Phone",
      merk: "Make",
      model: "Model",
      bouwjaar: "Year",
      type: "Type of work",
      typePlaat: "Bodywork",
      typeFull: "Full restoration",
      typeAdvies: "Advice",
      beschrijving: "Description",
      fotos: "Photos (max. 5)",
      submit: "Send request",
      sending: "Sending…",
    },
    success: {
      title: "Thank you for your request.",
      body: "We received your message. Baram will get back to you personally within two working days.",
    },
    error: "Something went wrong while sending. Please try again using the form.",
    photoTooMany: "Maximum five photos.",
    back: "Back to home",
    descriptionPlaceholder: "What would you like done? Any concerns or details to flag…",
    photosOptional: "Optional — helps us give you a quicker estimate.",
    photosChosen: (n: number) => (n === 1 ? "1 photo added" : `${n} photos added`),
    onlyImages: "Images only.",
    photoTooLarge: "One of the photos is larger than 8MB.",
    checkFields: "Please check the details you entered.",
    addPhotos: "Add photos",
    addPhotosHint: "Click or drag up to 5 photos here (JPG, PNG · max. 8MB each)",
    removePhoto: "Remove photo",
  },
  login: {
    title: "Client portal",
    body: "The secure portal for ongoing restorations is opening soon. You'll receive your login details by email once your project starts.",
    back: "Back to home",
  },
  portal: {
    loginTitle: "Client portal",
    loginSubline: "Sign in with your email and password.",
    emailLabel: "Email",
    emailPlaceholder: "name@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Your password",
    send: "Sign in",
    sending: "One moment…",
    forgot: "Forgot your password?",
    resetTitle: "Reset your password",
    resetSubline: "Enter your email and we'll send you a link to choose a new password.",
    resetSend: "Send reset link",
    resetSent: "Check your inbox — if the address is on file, you'll receive an email with a reset link.",
    backToLogin: "Back to sign in",
    newPasswordTitle: "Choose a new password",
    newPasswordLabel: "New password",
    newPasswordSave: "Save password",
    newPasswordSaved: "Password saved. Redirecting…",
    resetLinkExpired: "This reset link has expired. Please request a new one to choose your password.",
    resetLinkInvalid: "This reset link is no longer valid. Please request a new one to choose your password.",
    requestNewResetLink: "Request a new reset link",
    passwordTooShort: "Password must be at least 8 characters.",
    invalidCredentials: "Email or password is incorrect.",
    invalidEmail: "Please enter a valid email address.",
    sendError: "Something went wrong. Please try again using the form.",
    rateLimited: "You've just requested a link. Check your inbox or try again in a few minutes.",
    loginRateLimited: "Too many sign-in attempts. Wait a few minutes and try again, or use 'Forgot your password?'.",
    emailNotConfirmed: "Your email address hasn't been confirmed yet. Check your inbox for the confirmation email.",
    networkError: "Couldn't reach the server. Check your internet and try again.",
    loginUnknownError: "Sign-in failed. Please try again or click 'Forgot your password?'.",
    showPassword: "Show password",
    hidePassword: "Hide password",
    showShort: "Show",
    hideShort: "Hide",
    inviteWelcomeTitle: "Welcome — set your password",
    inviteWelcomeBody: "Choose a password to activate your access to the client portal.",
    settingPasswordFor: "You're setting a password for",
    verifyingLink: "Verifying recovery link…",
    linkExpiredAfterWait: "We couldn't verify your link. Please request a new one to continue.",
    notRegistered:
      "This email isn't in our system yet. Please contact Baram so we can set up your restoration.",
    overviewTitle: "Your restorations",
    overviewIntro: "Track the progress of your project, stage by stage.",
    empty: "Your restoration is being prepared — you'll receive an email as soon as the first update is ready.",
    backToOverview: "Back to overview",
    logout: "Sign out",
    welcome: "Welcome back",
    timelineTitle: "Timeline",
    noUpdates: "Not started yet.",
    statusLabels: {
      intake: "Intake",
      transport_out: "On the way to the workshop",
      in_workshop: "In the workshop",
      transport_return: "On the way back",
      delivered: "Delivered",
      archived: "Archived",
    },
  },
  recentWerk: {
    eyebrow: "Recent restoration",
    title: "Recent work.",
    intro: "Each restoration gets its own story here. We start with the very first project — and build out from there, classic by classic.",
    projectLabel: "Project 01 · 2024",
    projectTitle: "VW T2 Westfalia — from barn find to mountain pass.",
    projectBody:
      "An original Westfalia camper, brought in with the marks of years of standing still. The focus was on bodywork, pop-top roof and exterior — mechanics and interior stayed out of scope at this stage. Below the chronology, from first inspection to first drive through the mountains.",
    monthMay: "May 2024",
    monthJun: "June 2024",
    shots: {
      aankomst: { alt: "VW T2 Westfalia on arrival, rear hatch open", caption: "Arrival — Baram and the owner walk through the state of the bus." },
      inventaris: { alt: "VW T2 Westfalia front view in original two-tone paint", caption: "Inventory — all original parts kept wherever possible." },
      slaapdak: { alt: "VW T2 Westfalia side view with pop-top roof raised", caption: "Pop-top measured, canvas and hinges thoroughly checked." },
      ontmanteling: { alt: "VW T2 stripped of rubbers and windows, ready for sanding", caption: "Stripping — rubbers, windows and trim come off before the bodywork begins." },
      plamuur: { alt: "VW T2 in filler, masked for spraying", caption: "Filler and sanding — layer by layer until the surface is straight again." },
      eindcontrole: { alt: "Baram Maro and client beside the finished VW T2 Westfalia", caption: "Final check — Baram only signs off when every detail is right." },
      onderweg: { alt: "Restored VW T2 Westfalia in a mountainous landscape", caption: "On the road — the bus drives again where it belongs." },
    },
    comingSoonLabel: "Project 02 · coming soon",
    comingSoonBody:
      "The next classic is already in the workshop. Photos and story will follow as the work progresses.",
  },
  privacy: {
    eyebrow: "Legal",
    title: "Privacy & cookies",
    lastUpdate:
      "Last update: June 2026. This statement is a placeholder — final legal text will be added after review by Nomadix BV.",
    sections: {
      responsibleTitle: "Data controller",
      responsibleAddr: "Vredeplein 23, 3010 Kessel-Lo, Belgium",
      responsibleVat: "VAT BE 0694.858.510",
      contactLabel: "Contact:",
      dataTitle: "What data we collect",
      dataItems: [
        "Contact details you fill in yourself via the quote form (name, email, phone).",
        "Vehicle details and photos you send us for an estimate or restoration.",
        "Login details for the client portal (email address for magic-link login).",
      ],
      useTitle: "What we use them for",
      useBody:
        "Strictly to answer your quote request, to prepare and carry out your restoration, and to keep you informed of progress via the portal and email.",
      cookiesTitle: "Cookies",
      cookiesBody:
        "We only use functional cookies needed to sign in to the client portal. No tracking, no advertising cookies, no third-party analytics.",
      retentionTitle: "Retention",
      retentionBody:
        "Quote requests are kept for 24 months. Project and restoration files are kept for as long as the legal record-keeping obligation requires (7 years).",
      rightsTitle: "Your rights",
      rightsBefore: "You have the right to access, correct and delete your data. Send an email to ",
      rightsAfter: " and we'll respond within 30 days.",
    },
    back: "Back to home",
  },
  notFound: {
    eyebrow: "404",
    title: "This road's a dead end — but every classic deserves a second chance.",
    body: "The page you were looking for doesn't exist (any more). Head back to the workshop.",
    cta: "Back to home",
  },
  weldingVideo: {
    defaultAria: "Gas-welding in the workshop",
    play: "Play the video — gas-welding",
  },
  contact: {
    eyebrow: "Contact",
    title: "Send a message",
    intro: "A question, an idea, or just in the mood to talk about a classic? Drop us a line. Baram replies personally.",
    langLabel: "Language · reply by email",
    langNl: "Dutch",
    langEn: "English",
    nameLabel: "Name",
    emailLabel: "Email",
    messageLabel: "Message",
    submit: "Send message",
    sending: "Sending…",
    successTitle: "Thanks — your message is in.",
    successBody: "We'll also send you a portal invitation so you can find the reply and all follow-up messages in one place.",
    back: "Back to the site",
    error: "Something went wrong while sending. Please try again using the form.",
  },
};

export type Lang = "nl" | "en";
export const dict: Record<Lang, Copy> = { nl, en };
export const t = nl; // NL shortcut for server code, admin, and authenticated portal