// All site copy lives here. Public pages use `useT()` from `@/lib/i18n` and
// pick from `dict[lang]`. Server code and admin/portal pages still import the
// NL-only `t` shortcut.
export const nl = {
  brand: { name: "Yeketi Motorworks", tagline: "unity in craftsmanship" },
  nav: {
    home: "Home",
    diensten: "Diensten",
    restauratie: "Restauratie",
    over: "Over ons",
    offerte: "Offerte",
    portal: "Klantenportaal",
  },
  hero: {
    eyebrow: "Klassiekers — restauratie & plaatwerk",
    headline: "Vakmanschap dat verdwijnt, leeft hier verder.",
    subline:
      "Restauratie van klassiekers door meester-ambachtslieden — persoonlijk begeleid van inspectie tot aflevering.",
    ctaQuote: "Vraag een offerte",
    ctaFollow: "Volg een restauratie",
  },
  story: {
    eyebrow: "Het verhaal",
    title: "Een ambacht dat een tweede thuis vond.",
    body: [
      "Yeketi begon met één eenvoudige vaststelling: de klassiekers die wij in Europa koesteren, worden steeds zeldzamer hersteld. Niet door gebrek aan liefde, maar door gebrek aan tijd, aan handen, aan ruimte in de werkplaats.",
      "In de bergen van Koerdistan, in Iraq, werken nog steeds meester-ambachtslieden die het métier in de vingers hebben. Plaatwerkers, lassers, schilders — opgeleid in een traditie waar elke deuk met de hand wordt uitgeklopt. Wij brengen Europese auto's naar hen toe, en de auto die terugkomt is meer dan hersteld. Hij is opnieuw verteld.",
    ],
    pullQuote:
      "Een auto bewaart de adem van de mensen die hem maken. Daarom kiezen wij onze handen met zorg.",
    pullAttribution: "— Baram, oprichter",
  },
  process: {
    eyebrow: "Hoe het werkt",
    title: "Vijf stappen, één aanspreekpunt.",
    steps: [
      { n: "01", t: "Inspectie aan huis", d: "Wij komen langs, maken foto's, bespreken uw wensen en de staat van de wagen." },
      { n: "02", t: "Offerte & planning", d: "Een transparante offerte met afgebakende posten en een realistische tijdslijn." },
      { n: "03", t: "Transport", d: "Beveiligd, verzekerd transport van uw werkplaats of garage tot in de werkplaats in Koerdistan." },
      { n: "04", t: "Restauratie met foto-updates", d: "Iedere week beelden vanuit de werkplaats. U volgt elke fase mee, op uw eigen tempo." },
      { n: "05", t: "Aflevering", d: "De wagen komt terug, gepoetst en gekeurd, klaar voor de weg of voor de etalage." },
    ],
  },
  why: {
    eyebrow: "Waarom Yeketi",
    title: "Drie redenen die het verschil maken.",
    items: [
      {
        t: "Eerlijke prijs",
        d: "Restauratie aan een fractie van wat dezelfde ingreep in een Europese werkplaats kost — zonder ooit aan kwaliteit in te boeten.",
      },
      {
        t: "Kortere doorlooptijd",
        d: "Wij denken in weken en maanden, niet in jaren. De werkplaats werkt met meerdere ambachtslieden op één project.",
      },
      {
        t: "Persoonlijke begeleiding",
        d: "Eén aanspreekpunt, van eerste foto tot aflevering. Updates met beelden, in uw taal, op uw tempo.",
      },
    ],
  },
  recent: {
    eyebrow: "Recente restauratie",
    title: "Een VW T2, herboren.",
    body: "Eén maand werk: plaatwerkrestauratie en exterieur in originele kleurstelling. Lees het volledige verhaal.",
    cta: "Bekijk de restauratie",
    href: "/recent-werk",
  },
  footer: {
    columnsTitle: "Yeketi Motorworks",
    tagline: "unity in craftsmanship",
    contact: "Vredeplein 23, 3010 Kessel-Lo (BE)",
    email: "hallo@yeketi.eu",
    instagram: "Instagram",
    rights: "© 2026 Yeketi Motorworks",
    kvk: "BTW BE 0694.858.510",
  },
  diensten: {
    eyebrow: "Diensten",
    title: "Twee paden. Hetzelfde vakmanschap.",
    intro: "Of u nu een specifiek paneel wilt laten herstellen of een volledige restauratie wenst — wij vertrekken altijd van een gesprek en een eerlijke inschatting.",
    tiers: [
      {
        t: "Plaatwerk & carrosserie",
        sub: "Voor wie één element wil herstellen.",
        items: [
          "Uitdeuken met de hand, geen plamuur waar het niet hoort",
          "Lassen en vernieuwen van rotte panelen",
          "Voorbereiding voor spuitwerk, of volledige aflakking",
          "Chroomwerk en sierlijsten in originele staat",
        ],
        cta: "Vraag een offerte",
      },
      {
        t: "Volledige restauratie",
        sub: "Voor wie de wagen terug wil zoals hij ooit was.",
        items: [
          "Demontage tot op het naakte chassis",
          "Behandeling tegen corrosie, zinkprimer, nieuwe lak",
          "Mechaniek, elektriciteit en interieur in originele specificaties",
          "Eindkeuring, poetsbeurt, transport tot voor uw deur",
        ],
        cta: "Plan een gesprek",
      },
    ],
    faqTitle: "Veelgestelde vragen",
    faq: [
      { q: "Hoe verloopt het transport en de verzekering?", a: "Wij werken met gespecialiseerde transporteurs voor klassiekers. De wagen wordt verzekerd op de afgesproken waarde, deur tot deur. U krijgt vooraf alle documenten ter inzage." },
      { q: "Wat is een realistische doorlooptijd?", a: "Plaatwerk: enkele weken tot twee maanden. Volledige restauratie: drie tot negen maanden, afhankelijk van de staat en de mate van originaliteit die u wenst." },
      { q: "Hoe houden jullie mij op de hoogte?", a: "U krijgt wekelijks foto's en, op vraag, een korte videoboodschap uit de werkplaats. Eén aanspreekpunt in België voor al uw vragen." },
      { q: "Kan ik in schijven betalen?", a: "Ja. Wij werken standaard met drie schijven: bij start, halverwege en bij aflevering. Schijven zijn gekoppeld aan vooraf afgesproken mijlpalen." },
      { q: "Welke garantie geven jullie op het werk?", a: "Twee jaar garantie op plaatwerk en lakwerk, één jaar op mechanische ingrepen. Wij blijven aanspreekbaar, ook na aflevering." },
    ],
  },
  caseT2: {
    eyebrow: "Onze werkwijze",
    title: "Restauratie — van aankomst tot aflevering.",
    lead: "Negen maanden, meerdere ambachtslieden, één doel: een klassieker terugbrengen in de staat waarin hij ooit de fabriek verliet — zonder de geschiedenis uit te vegen.",
    chapters: [
      { date: "Maand 1", t: "Aankomst", d: "De wagen arriveert in de werkplaats. Eerste inventaris: een nauwgezette inspectie van carrosserie, chassis en mechaniek. Alle aandachtspunten worden gefotografeerd en met de eigenaar besproken voor er één bout wordt losgedraaid." },
      { date: "Maand 2 – 4", t: "Plaatwerk", d: "Rotte panelen worden vakkundig uitgesneden en met de hand opnieuw gevormd uit nieuw staal, volgens de originele profielen. Geen plamuur waar het niet hoort — elke deuk wordt geklopt zoals het hoort bij een klassieker." },
      { date: "Maand 5", t: "Mechaniek", d: "Het motorblok wordt volledig gereviseerd. Pakkingen, zuigers en kleppen worden vernieuwd; originele onderdelen worden waar mogelijk gerestaureerd in plaats van vervangen, om het karakter van de wagen te behouden." },
      { date: "Maand 6 – 7", t: "Lakwerk", d: "Meerdere lagen primer, plamuur en lak — exact volgens de originele kleurcode van de fabrikant. Met de hand gepolijst tot de oorspronkelijke diepte en glans terug zichtbaar zijn." },
      { date: "Maand 8", t: "Interieur", d: "Nieuwe binnenbekleding op maat in originele stof en kleur. Stuur, pedalen en schakelpook blijven het origineel — alles wat de eigenaar dagelijks aanraakt, draagt de patina van vijftig jaar geschiedenis." },
      { date: "Maand 9", t: "Aflevering", d: "Eindcontrole en beveiligd transport tot voor de deur. De wagen rijdt opnieuw zijn eerste kilometers — een klassieker die nog generaties mee kan." },
    ],
    closing:
      "Restauratie is geen poging om de tijd terug te draaien. Het is een belofte dat het verhaal verder mag gaan.",
  },
  over: {
    eyebrow: "Over Yeketi",
    title: "Yeketi betekent eenheid. Eenheid in vakmanschap.",
    body: [
      "Yeketi is een Koerdisch woord voor eenheid. Het kiezen van die naam was geen marketingbeslissing — het was een principe. Wij brengen twee werelden samen: Europese eigenaars die hun klassieker willen koesteren, en een netwerk van Koerdische meester-ambachtslieden die het oude métier nog in de vingers hebben.",
      "De werkplaats ligt in de buurt van Erbil, in de Koerdistan-regio van Iraq. Het is een rustige plek, ver van de massaproductie, waar men nog tijd neemt om naar metaal te luisteren. De ambachtslieden — sommigen al dertig jaar in het vak — werken met de geduldige nauwkeurigheid die deze auto's verdienen.",
      "Vanuit België coördineren wij elk project persoonlijk. Wij komen langs voor de inspectie, regelen het transport, en zijn uw enige aanspreekpunt zolang de wagen weg is. U hoort van ons in het Nederlands. U krijgt foto's per week, en een eerlijk antwoord wanneer u erom vraagt.",
    ],
    founderName: "Baram — oprichter",
    founderQuote:
      "Ik wil dat mijn klanten hun wagen op een dag aan hun kleinkinderen kunnen doorgeven. Dat is de enige reden dat dit bestaat.",
  },
  offerte: {
    eyebrow: "Offerte aanvragen",
    title: "Vertel ons over uw klassieker.",
    intro: "Geen verplichting, geen verkoopstruc. U krijgt binnen twee werkdagen een persoonlijke reactie van Baram.",
    labels: {
      naam: "Naam",
      email: "E-mail",
      telefoon: "Telefoon",
      merk: "Merk",
      model: "Model",
      bouwjaar: "Bouwjaar",
      type: "Type werk",
      typePlaat: "Plaatwerk",
      typeFull: "Volledige restauratie",
      typeAdvies: "Advies",
      beschrijving: "Beschrijving",
      fotos: "Foto's (max. 5)",
      submit: "Verstuur aanvraag",
      sending: "Versturen…",
    },
    success: {
      title: "Bedankt voor uw aanvraag.",
      body: "Wij hebben uw bericht goed ontvangen. Baram neemt binnen twee werkdagen persoonlijk contact op.",
    },
    error: "Er ging iets mis bij het versturen. Probeer het opnieuw of stuur een e-mail naar hallo@yeketi.eu.",
    photoTooMany: "Maximaal vijf foto's.",
  },
  login: {
    title: "Klantenportaal",
    body: "Het beveiligde portaal voor lopende restauraties opent binnenkort. U ontvangt uw inloggegevens per e-mail zodra uw project van start gaat.",
    back: "Terug naar home",
  },
  portal: {
    loginTitle: "Klantenportaal",
    loginSubline: "Log in met je e-mailadres en wachtwoord.",
    emailLabel: "E-mailadres",
    emailPlaceholder: "naam@voorbeeld.be",
    passwordLabel: "Wachtwoord",
    passwordPlaceholder: "Je wachtwoord",
    send: "Inloggen",
    sending: "Bezig…",
    forgot: "Wachtwoord vergeten?",
    resetTitle: "Wachtwoord opnieuw instellen",
    resetSubline: "Vul je e-mailadres in en we sturen je een link om een nieuw wachtwoord te kiezen.",
    resetSend: "Stuur resetlink",
    resetSent: "Check je inbox — als het adres bij ons bekend is, ontvang je een e-mail met een resetlink.",
    backToLogin: "Terug naar inloggen",
    newPasswordTitle: "Kies een nieuw wachtwoord",
    newPasswordLabel: "Nieuw wachtwoord",
    newPasswordSave: "Wachtwoord opslaan",
    newPasswordSaved: "Wachtwoord opgeslagen. Je wordt doorgestuurd…",
    resetLinkExpired: "Deze resetlink is verlopen. Vraag even een nieuwe link aan om je wachtwoord te kiezen.",
    resetLinkInvalid: "Deze resetlink is niet meer geldig. Vraag even een nieuwe link aan om je wachtwoord te kiezen.",
    requestNewResetLink: "Nieuwe resetlink aanvragen",
    passwordTooShort: "Wachtwoord moet minstens 8 tekens bevatten.",
    invalidCredentials: "E-mailadres of wachtwoord klopt niet.",
    invalidEmail: "Vul een geldig e-mailadres in.",
    sendError: "Er ging iets mis. Probeer het opnieuw of mail hallo@yeketi.eu.",
    rateLimited: "Je hebt net al een link opgevraagd. Controleer je mailbox of probeer over een paar minuten opnieuw.",
    showPassword: "Toon wachtwoord",
    hidePassword: "Verberg wachtwoord",
    inviteWelcomeTitle: "Welkom — stel je wachtwoord in",
    inviteWelcomeBody: "Kies een wachtwoord om je toegang tot het klantenportaal te activeren.",
    settingPasswordFor: "Je stelt een wachtwoord in voor",
    verifyingLink: "Recovery-link wordt geverifieerd…",
    linkExpiredAfterWait: "We konden je link niet verifiëren. Vraag een nieuwe link aan om verder te gaan.",
    notRegistered:
      "Dit e-mailadres staat nog niet in ons systeem. Neem contact op met Baram zodat we je restauratie kunnen klaarzetten.",
    overviewTitle: "Jouw restauraties",
    overviewIntro: "Volg de voortgang van je project, fase per fase.",
    empty: "Je restauratie wordt klaargezet — je ontvangt een e-mail zodra de eerste update er is.",
    backToOverview: "Terug naar overzicht",
    logout: "Uitloggen",
    welcome: "Welkom terug",
    timelineTitle: "Tijdlijn",
    noUpdates: "Nog niet gestart.",
    statusLabels: {
      intake: "Intake",
      transport_out: "Onderweg naar werkplaats",
      in_workshop: "In de werkplaats",
      transport_return: "Onderweg terug",
      delivered: "Afgeleverd",
      archived: "Gearchiveerd",
    },
  },
};

export type Copy = typeof nl;

export const en: Copy = {
  brand: { name: "Yeketi Motorworks", tagline: "unity in craftsmanship" },
  nav: {
    home: "Home",
    diensten: "Services",
    restauratie: "Restoration",
    over: "About",
    offerte: "Quote",
    portal: "Client portal",
  },
  hero: {
    eyebrow: "Classics — restoration & bodywork",
    headline: "Craftsmanship that's disappearing, lives on here.",
    subline:
      "Restoration of classic cars by master craftsmen — personally guided from inspection to delivery.",
    ctaQuote: "Request a quote",
    ctaFollow: "Follow a restoration",
  },
  story: {
    eyebrow: "The story",
    title: "A craft that found a second home.",
    body: [
      "Yeketi began with one simple observation: the classic cars we cherish in Europe are restored less and less. Not for lack of love, but for lack of time, of hands, of room in the workshop.",
      "In the mountains of Kurdistan, in Iraq, master craftsmen still work who carry the trade in their fingers. Panel beaters, welders, painters — trained in a tradition where every dent is tapped out by hand. We bring European cars to them, and the car that comes back is more than restored. It is retold.",
    ],
    pullQuote:
      "A car carries the breath of the people who built it. That is why we choose our hands with care.",
    pullAttribution: "— Baram, founder",
  },
  process: {
    eyebrow: "How it works",
    title: "Five steps, one point of contact.",
    steps: [
      { n: "01", t: "On-site inspection", d: "We come to you, take photos, and discuss your wishes and the state of the car." },
      { n: "02", t: "Quote & planning", d: "A transparent quote with itemised work and a realistic timeline." },
      { n: "03", t: "Transport", d: "Secured, insured transport from your garage to the workshop in Kurdistan." },
      { n: "04", t: "Restoration with photo updates", d: "Weekly images from the workshop. You follow every stage at your own pace." },
      { n: "05", t: "Delivery", d: "The car returns, detailed and inspected, ready for the road or the showroom." },
    ],
  },
  why: {
    eyebrow: "Why Yeketi",
    title: "Three reasons that make the difference.",
    items: [
      { t: "Fair price", d: "Restoration at a fraction of what the same work costs in a European workshop — without ever compromising on quality." },
      { t: "Shorter lead time", d: "We think in weeks and months, not years. The workshop puts several craftsmen on one project." },
      { t: "Personal guidance", d: "One point of contact, from the first photo to delivery. Updates with images, in your language, at your pace." },
    ],
  },
  recent: {
    eyebrow: "Recent restoration",
    title: "A VW T2, reborn.",
    body: "One month of work: bodywork restoration and exterior in the original colour scheme. Read the full story.",
    cta: "View the restoration",
    href: "/recent-werk",
  },
  footer: {
    columnsTitle: "Yeketi Motorworks",
    tagline: "unity in craftsmanship",
    contact: "Vredeplein 23, 3010 Kessel-Lo (BE)",
    email: "hallo@yeketi.eu",
    instagram: "Instagram",
    rights: "© 2026 Yeketi Motorworks",
    kvk: "VAT BE 0694.858.510",
  },
  diensten: {
    eyebrow: "Services",
    title: "Two paths. The same craftsmanship.",
    intro: "Whether you want a single panel repaired or a full restoration — we always start with a conversation and an honest assessment.",
    tiers: [
      {
        t: "Bodywork & panel beating",
        sub: "For those who want one element restored.",
        items: [
          "Hand-tapped dent removal, no filler where it doesn't belong",
          "Welding and replacing rusted panels",
          "Prep work for painting, or full respray",
          "Chrome and trim restored to original condition",
        ],
        cta: "Request a quote",
      },
      {
        t: "Full restoration",
        sub: "For those who want the car back the way it once was.",
        items: [
          "Disassembly down to the bare chassis",
          "Corrosion treatment, zinc primer, new paint",
          "Mechanics, electrics and interior to original specification",
          "Final inspection, detailing, transport to your door",
        ],
        cta: "Schedule a call",
      },
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "How do transport and insurance work?", a: "We work with specialist classic-car transporters. The car is insured at the agreed value, door to door. You receive all documents in advance." },
      { q: "What is a realistic lead time?", a: "Bodywork: a few weeks to two months. Full restoration: three to nine months, depending on the condition and the level of originality you want." },
      { q: "How do you keep me informed?", a: "You get weekly photos and, on request, a short video message from the workshop. One point of contact in Belgium for all your questions." },
      { q: "Can I pay in instalments?", a: "Yes. We work in three instalments by default: at start, halfway, and on delivery. Instalments are tied to pre-agreed milestones." },
      { q: "What warranty do you offer?", a: "Two years on bodywork and paintwork, one year on mechanical work. We remain available, also after delivery." },
    ],
  },
  caseT2: {
    eyebrow: "Our way of working",
    title: "Restoration — from arrival to delivery.",
    lead: "Nine months, several craftsmen, one goal: to bring a classic back to the state in which it once left the factory — without erasing its history.",
    chapters: [
      { date: "Month 1", t: "Arrival", d: "The car arrives at the workshop. First inventory: a thorough inspection of body, chassis and mechanics. Every point of attention is photographed and discussed with the owner before a single bolt is loosened." },
      { date: "Month 2 – 4", t: "Bodywork", d: "Rusted panels are cut out and reshaped by hand from new steel, true to the original profiles. No filler where it doesn't belong — every dent tapped out the way a classic deserves." },
      { date: "Month 5", t: "Mechanics", d: "The engine block is fully rebuilt. Gaskets, pistons and valves are renewed; original parts are restored rather than replaced wherever possible, to preserve the character of the car." },
      { date: "Month 6 – 7", t: "Paintwork", d: "Multiple layers of primer, filler and paint — exactly to the manufacturer's original colour code. Hand-polished until the original depth and gloss are visible again." },
      { date: "Month 8", t: "Interior", d: "New upholstery made to measure in original fabric and colour. Steering wheel, pedals and gear lever stay original — everything the owner touches daily carries the patina of fifty years of history." },
      { date: "Month 9", t: "Delivery", d: "Final inspection and secured transport to your door. The car drives its first kilometres again — a classic ready for generations to come." },
    ],
    closing:
      "Restoration is not an attempt to turn back time. It is a promise that the story may continue.",
  },
  over: {
    eyebrow: "About Yeketi",
    title: "Yeketi means unity. Unity in craftsmanship.",
    body: [
      "Yeketi is a Kurdish word for unity. Choosing that name was not a marketing decision — it was a principle. We bring two worlds together: European owners who want to cherish their classic car, and a network of Kurdish master craftsmen who still carry the old trade in their hands.",
      "The workshop is located near Erbil, in the Kurdistan region of Iraq. It is a quiet place, far from mass production, where people still take the time to listen to metal. The craftsmen — some with thirty years in the trade — work with the patient precision these cars deserve.",
      "From Belgium we coordinate every project personally. We come by for the inspection, arrange transport, and are your only point of contact while the car is away. You hear from us in English or Dutch. You get photos every week, and an honest answer when you ask for one.",
    ],
    founderName: "Baram — founder",
    founderQuote:
      "I want my clients to be able to hand their car down to their grandchildren one day. That is the only reason this exists.",
  },
  offerte: {
    eyebrow: "Request a quote",
    title: "Tell us about your classic.",
    intro: "No obligation, no sales pitch. You'll get a personal response from Baram within two working days.",
    labels: {
      naam: "Name",
      email: "Email",
      telefoon: "Phone",
      merk: "Make",
      model: "Model",
      bouwjaar: "Year",
      type: "Type of work",
      typePlaat: "Bodywork",
      typeFull: "Full restoration",
      typeAdvies: "Advice",
      beschrijving: "Description",
      fotos: "Photos (max. 5)",
      submit: "Send request",
      sending: "Sending…",
    },
    success: {
      title: "Thank you for your request.",
      body: "We received your message. Baram will get back to you personally within two working days.",
    },
    error: "Something went wrong while sending. Please try again or email hallo@yeketi.eu.",
    photoTooMany: "Maximum five photos.",
  },
  login: {
    title: "Client portal",
    body: "The secure portal for ongoing restorations is opening soon. You'll receive your login details by email once your project starts.",
    back: "Back to home",
  },
  portal: {
    loginTitle: "Client portal",
    loginSubline: "Sign in with your email and password.",
    emailLabel: "Email",
    emailPlaceholder: "name@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Your password",
    send: "Sign in",
    sending: "One moment…",
    forgot: "Forgot your password?",
    resetTitle: "Reset your password",
    resetSubline: "Enter your email and we'll send you a link to choose a new password.",
    resetSend: "Send reset link",
    resetSent: "Check your inbox — if the address is on file, you'll receive an email with a reset link.",
    backToLogin: "Back to sign in",
    newPasswordTitle: "Choose a new password",
    newPasswordLabel: "New password",
    newPasswordSave: "Save password",
    newPasswordSaved: "Password saved. Redirecting…",
    resetLinkExpired: "This reset link has expired. Please request a new one to choose your password.",
    resetLinkInvalid: "This reset link is no longer valid. Please request a new one to choose your password.",
    requestNewResetLink: "Request a new reset link",
    passwordTooShort: "Password must be at least 8 characters.",
    invalidCredentials: "Email or password is incorrect.",
    invalidEmail: "Please enter a valid email address.",
    sendError: "Something went wrong. Please try again or email hallo@yeketi.eu.",
    rateLimited: "You've just requested a link. Check your inbox or try again in a few minutes.",
    showPassword: "Show password",
    hidePassword: "Hide password",
    inviteWelcomeTitle: "Welcome — set your password",
    inviteWelcomeBody: "Choose a password to activate your access to the client portal.",
    settingPasswordFor: "You're setting a password for",
    verifyingLink: "Verifying recovery link…",
    linkExpiredAfterWait: "We couldn't verify your link. Please request a new one to continue.",
    notRegistered:
      "This email isn't in our system yet. Please contact Baram so we can set up your restoration.",
    overviewTitle: "Your restorations",
    overviewIntro: "Track the progress of your project, stage by stage.",
    empty: "Your restoration is being prepared — you'll receive an email as soon as the first update is ready.",
    backToOverview: "Back to overview",
    logout: "Sign out",
    welcome: "Welcome back",
    timelineTitle: "Timeline",
    noUpdates: "Not started yet.",
    statusLabels: {
      intake: "Intake",
      transport_out: "On the way to the workshop",
      in_workshop: "In the workshop",
      transport_return: "On the way back",
      delivered: "Delivered",
      archived: "Archived",
    },
  },
};

export type Lang = "nl" | "en";
export const dict: Record<Lang, Copy> = { nl, en };
export const t = nl; // NL shortcut for server code, admin, and authenticated portal