/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecentWerkRouteImport } from './routes/recent-werk'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OverRouteImport } from './routes/over'
import { Route as OfferteRouteImport } from './routes/offerte'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestauratieVwT2RouteImport } from './routes/restauratie.vw-t2'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPortaalIndexRouteImport } from './routes/_authenticated/portaal.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedPortaalProjectIdRouteImport } from './routes/_authenticated/portaal.$projectId'
import { Route as AuthenticatedAdminOffertesRouteImport } from './routes/_authenticated/admin/offertes'
import { Route as AuthenticatedAdminKlantenRouteImport } from './routes/_authenticated/admin/klanten'
import { Route as AuthenticatedAdminRecentWerkIndexRouteImport } from './routes/_authenticated/admin/recent-werk.index'
import { Route as AuthenticatedAdminQuotesIndexRouteImport } from './routes/_authenticated/admin/quotes.index'
import { Route as AuthenticatedAdminProjectenIndexRouteImport } from './routes/_authenticated/admin/projecten.index'
import { Route as AuthenticatedAdminBerichtenIndexRouteImport } from './routes/_authenticated/admin/berichten.index'
import { Route as AuthenticatedPortaalOfferteIdRouteImport } from './routes/_authenticated/portaal.offerte.$id'
import { Route as AuthenticatedAdminRecentWerkIdRouteImport } from './routes/_authenticated/admin/recent-werk.$id'
import { Route as AuthenticatedAdminQuotesIdRouteImport } from './routes/_authenticated/admin/quotes.$id'
import { Route as AuthenticatedAdminProjectenIdRouteImport } from './routes/_authenticated/admin/projecten.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentWerkRoute = RecentWerkRouteImport.update({
  id: '/recent-werk',
  path: '/recent-werk',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OverRoute = OverRouteImport.update({
  id: '/over',
  path: '/over',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferteRoute = OfferteRouteImport.update({
  id: '/offerte',
  path: '/offerte',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestauratieVwT2Route = RestauratieVwT2RouteImport.update({
  id: '/restauratie/vw-t2',
  path: '/restauratie/vw-t2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortaalIndexRoute =
  AuthenticatedPortaalIndexRouteImport.update({
    id: '/portaal/',
    path: '/portaal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedPortaalProjectIdRoute =
  AuthenticatedPortaalProjectIdRouteImport.update({
    id: '/portaal/$projectId',
    path: '/portaal/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOffertesRoute =
  AuthenticatedAdminOffertesRouteImport.update({
    id: '/offertes',
    path: '/offertes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKlantenRoute =
  AuthenticatedAdminKlantenRouteImport.update({
    id: '/klanten',
    path: '/klanten',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRecentWerkIndexRoute =
  AuthenticatedAdminRecentWerkIndexRouteImport.update({
    id: '/recent-werk/',
    path: '/recent-werk/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuotesIndexRoute =
  AuthenticatedAdminQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProjectenIndexRoute =
  AuthenticatedAdminProjectenIndexRouteImport.update({
    id: '/projecten/',
    path: '/projecten/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBerichtenIndexRoute =
  AuthenticatedAdminBerichtenIndexRouteImport.update({
    id: '/berichten/',
    path: '/berichten/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedPortaalOfferteIdRoute =
  AuthenticatedPortaalOfferteIdRouteImport.update({
    id: '/portaal/offerte/$id',
    path: '/portaal/offerte/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRecentWerkIdRoute =
  AuthenticatedAdminRecentWerkIdRouteImport.update({
    id: '/recent-werk/$id',
    path: '/recent-werk/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuotesIdRoute =
  AuthenticatedAdminQuotesIdRouteImport.update({
    id: '/quotes/$id',
    path: '/quotes/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProjectenIdRoute =
  AuthenticatedAdminProjectenIdRouteImport.update({
    id: '/projecten/$id',
    path: '/projecten/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diensten': typeof DienstenRoute
  '/login': typeof LoginRoute
  '/offerte': typeof OfferteRoute
  '/over': typeof OverRoute
  '/privacy': typeof PrivacyRoute
  '/recent-werk': typeof RecentWerkRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/restauratie/vw-t2': typeof RestauratieVwT2Route
  '/admin/klanten': typeof AuthenticatedAdminKlantenRoute
  '/admin/offertes': typeof AuthenticatedAdminOffertesRoute
  '/portaal/$projectId': typeof AuthenticatedPortaalProjectIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portaal/': typeof AuthenticatedPortaalIndexRoute
  '/admin/projecten/$id': typeof AuthenticatedAdminProjectenIdRoute
  '/admin/quotes/$id': typeof AuthenticatedAdminQuotesIdRoute
  '/admin/recent-werk/$id': typeof AuthenticatedAdminRecentWerkIdRoute
  '/portaal/offerte/$id': typeof AuthenticatedPortaalOfferteIdRoute
  '/admin/berichten/': typeof AuthenticatedAdminBerichtenIndexRoute
  '/admin/projecten/': typeof AuthenticatedAdminProjectenIndexRoute
  '/admin/quotes/': typeof AuthenticatedAdminQuotesIndexRoute
  '/admin/recent-werk/': typeof AuthenticatedAdminRecentWerkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diensten': typeof DienstenRoute
  '/login': typeof LoginRoute
  '/offerte': typeof OfferteRoute
  '/over': typeof OverRoute
  '/privacy': typeof PrivacyRoute
  '/recent-werk': typeof RecentWerkRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/restauratie/vw-t2': typeof RestauratieVwT2Route
  '/admin/klanten': typeof AuthenticatedAdminKlantenRoute
  '/admin/offertes': typeof AuthenticatedAdminOffertesRoute
  '/portaal/$projectId': typeof AuthenticatedPortaalProjectIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portaal': typeof AuthenticatedPortaalIndexRoute
  '/admin/projecten/$id': typeof AuthenticatedAdminProjectenIdRoute
  '/admin/quotes/$id': typeof AuthenticatedAdminQuotesIdRoute
  '/admin/recent-werk/$id': typeof AuthenticatedAdminRecentWerkIdRoute
  '/portaal/offerte/$id': typeof AuthenticatedPortaalOfferteIdRoute
  '/admin/berichten': typeof AuthenticatedAdminBerichtenIndexRoute
  '/admin/projecten': typeof AuthenticatedAdminProjectenIndexRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesIndexRoute
  '/admin/recent-werk': typeof AuthenticatedAdminRecentWerkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/diensten': typeof DienstenRoute
  '/login': typeof LoginRoute
  '/offerte': typeof OfferteRoute
  '/over': typeof OverRoute
  '/privacy': typeof PrivacyRoute
  '/recent-werk': typeof RecentWerkRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/restauratie/vw-t2': typeof RestauratieVwT2Route
  '/_authenticated/admin/klanten': typeof AuthenticatedAdminKlantenRoute
  '/_authenticated/admin/offertes': typeof AuthenticatedAdminOffertesRoute
  '/_authenticated/portaal/$projectId': typeof AuthenticatedPortaalProjectIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portaal/': typeof AuthenticatedPortaalIndexRoute
  '/_authenticated/admin/projecten/$id': typeof AuthenticatedAdminProjectenIdRoute
  '/_authenticated/admin/quotes/$id': typeof AuthenticatedAdminQuotesIdRoute
  '/_authenticated/admin/recent-werk/$id': typeof AuthenticatedAdminRecentWerkIdRoute
  '/_authenticated/portaal/offerte/$id': typeof AuthenticatedPortaalOfferteIdRoute
  '/_authenticated/admin/berichten/': typeof AuthenticatedAdminBerichtenIndexRoute
  '/_authenticated/admin/projecten/': typeof AuthenticatedAdminProjectenIndexRoute
  '/_authenticated/admin/quotes/': typeof AuthenticatedAdminQuotesIndexRoute
  '/_authenticated/admin/recent-werk/': typeof AuthenticatedAdminRecentWerkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diensten'
    | '/login'
    | '/offerte'
    | '/over'
    | '/privacy'
    | '/recent-werk'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/restauratie/vw-t2'
    | '/admin/klanten'
    | '/admin/offertes'
    | '/portaal/$projectId'
    | '/admin/'
    | '/portaal/'
    | '/admin/projecten/$id'
    | '/admin/quotes/$id'
    | '/admin/recent-werk/$id'
    | '/portaal/offerte/$id'
    | '/admin/berichten/'
    | '/admin/projecten/'
    | '/admin/quotes/'
    | '/admin/recent-werk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diensten'
    | '/login'
    | '/offerte'
    | '/over'
    | '/privacy'
    | '/recent-werk'
    | '/reset-password'
    | '/sitemap.xml'
    | '/restauratie/vw-t2'
    | '/admin/klanten'
    | '/admin/offertes'
    | '/portaal/$projectId'
    | '/admin'
    | '/portaal'
    | '/admin/projecten/$id'
    | '/admin/quotes/$id'
    | '/admin/recent-werk/$id'
    | '/portaal/offerte/$id'
    | '/admin/berichten'
    | '/admin/projecten'
    | '/admin/quotes'
    | '/admin/recent-werk'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/diensten'
    | '/login'
    | '/offerte'
    | '/over'
    | '/privacy'
    | '/recent-werk'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/restauratie/vw-t2'
    | '/_authenticated/admin/klanten'
    | '/_authenticated/admin/offertes'
    | '/_authenticated/portaal/$projectId'
    | '/_authenticated/admin/'
    | '/_authenticated/portaal/'
    | '/_authenticated/admin/projecten/$id'
    | '/_authenticated/admin/quotes/$id'
    | '/_authenticated/admin/recent-werk/$id'
    | '/_authenticated/portaal/offerte/$id'
    | '/_authenticated/admin/berichten/'
    | '/_authenticated/admin/projecten/'
    | '/_authenticated/admin/quotes/'
    | '/_authenticated/admin/recent-werk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DienstenRoute: typeof DienstenRoute
  LoginRoute: typeof LoginRoute
  OfferteRoute: typeof OfferteRoute
  OverRoute: typeof OverRoute
  PrivacyRoute: typeof PrivacyRoute
  RecentWerkRoute: typeof RecentWerkRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RestauratieVwT2Route: typeof RestauratieVwT2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent-werk': {
      id: '/recent-werk'
      path: '/recent-werk'
      fullPath: '/recent-werk'
      preLoaderRoute: typeof RecentWerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over': {
      id: '/over'
      path: '/over'
      fullPath: '/over'
      preLoaderRoute: typeof OverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerte': {
      id: '/offerte'
      path: '/offerte'
      fullPath: '/offerte'
      preLoaderRoute: typeof OfferteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restauratie/vw-t2': {
      id: '/restauratie/vw-t2'
      path: '/restauratie/vw-t2'
      fullPath: '/restauratie/vw-t2'
      preLoaderRoute: typeof RestauratieVwT2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portaal/': {
      id: '/_authenticated/portaal/'
      path: '/portaal'
      fullPath: '/portaal/'
      preLoaderRoute: typeof AuthenticatedPortaalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/portaal/$projectId': {
      id: '/_authenticated/portaal/$projectId'
      path: '/portaal/$projectId'
      fullPath: '/portaal/$projectId'
      preLoaderRoute: typeof AuthenticatedPortaalProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/offertes': {
      id: '/_authenticated/admin/offertes'
      path: '/offertes'
      fullPath: '/admin/offertes'
      preLoaderRoute: typeof AuthenticatedAdminOffertesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/klanten': {
      id: '/_authenticated/admin/klanten'
      path: '/klanten'
      fullPath: '/admin/klanten'
      preLoaderRoute: typeof AuthenticatedAdminKlantenRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/recent-werk/': {
      id: '/_authenticated/admin/recent-werk/'
      path: '/recent-werk'
      fullPath: '/admin/recent-werk/'
      preLoaderRoute: typeof AuthenticatedAdminRecentWerkIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/quotes/': {
      id: '/_authenticated/admin/quotes/'
      path: '/quotes'
      fullPath: '/admin/quotes/'
      preLoaderRoute: typeof AuthenticatedAdminQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/projecten/': {
      id: '/_authenticated/admin/projecten/'
      path: '/projecten'
      fullPath: '/admin/projecten/'
      preLoaderRoute: typeof AuthenticatedAdminProjectenIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/berichten/': {
      id: '/_authenticated/admin/berichten/'
      path: '/berichten'
      fullPath: '/admin/berichten/'
      preLoaderRoute: typeof AuthenticatedAdminBerichtenIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/portaal/offerte/$id': {
      id: '/_authenticated/portaal/offerte/$id'
      path: '/portaal/offerte/$id'
      fullPath: '/portaal/offerte/$id'
      preLoaderRoute: typeof AuthenticatedPortaalOfferteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/recent-werk/$id': {
      id: '/_authenticated/admin/recent-werk/$id'
      path: '/recent-werk/$id'
      fullPath: '/admin/recent-werk/$id'
      preLoaderRoute: typeof AuthenticatedAdminRecentWerkIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/quotes/$id': {
      id: '/_authenticated/admin/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/admin/quotes/$id'
      preLoaderRoute: typeof AuthenticatedAdminQuotesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/projecten/$id': {
      id: '/_authenticated/admin/projecten/$id'
      path: '/projecten/$id'
      fullPath: '/admin/projecten/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectenIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminKlantenRoute: typeof AuthenticatedAdminKlantenRoute
  AuthenticatedAdminOffertesRoute: typeof AuthenticatedAdminOffertesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProjectenIdRoute: typeof AuthenticatedAdminProjectenIdRoute
  AuthenticatedAdminQuotesIdRoute: typeof AuthenticatedAdminQuotesIdRoute
  AuthenticatedAdminRecentWerkIdRoute: typeof AuthenticatedAdminRecentWerkIdRoute
  AuthenticatedAdminBerichtenIndexRoute: typeof AuthenticatedAdminBerichtenIndexRoute
  AuthenticatedAdminProjectenIndexRoute: typeof AuthenticatedAdminProjectenIndexRoute
  AuthenticatedAdminQuotesIndexRoute: typeof AuthenticatedAdminQuotesIndexRoute
  AuthenticatedAdminRecentWerkIndexRoute: typeof AuthenticatedAdminRecentWerkIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminKlantenRoute: AuthenticatedAdminKlantenRoute,
    AuthenticatedAdminOffertesRoute: AuthenticatedAdminOffertesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminProjectenIdRoute: AuthenticatedAdminProjectenIdRoute,
    AuthenticatedAdminQuotesIdRoute: AuthenticatedAdminQuotesIdRoute,
    AuthenticatedAdminRecentWerkIdRoute: AuthenticatedAdminRecentWerkIdRoute,
    AuthenticatedAdminBerichtenIndexRoute:
      AuthenticatedAdminBerichtenIndexRoute,
    AuthenticatedAdminProjectenIndexRoute:
      AuthenticatedAdminProjectenIndexRoute,
    AuthenticatedAdminQuotesIndexRoute: AuthenticatedAdminQuotesIndexRoute,
    AuthenticatedAdminRecentWerkIndexRoute:
      AuthenticatedAdminRecentWerkIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedPortaalProjectIdRoute: typeof AuthenticatedPortaalProjectIdRoute
  AuthenticatedPortaalIndexRoute: typeof AuthenticatedPortaalIndexRoute
  AuthenticatedPortaalOfferteIdRoute: typeof AuthenticatedPortaalOfferteIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedPortaalProjectIdRoute: AuthenticatedPortaalProjectIdRoute,
  AuthenticatedPortaalIndexRoute: AuthenticatedPortaalIndexRoute,
  AuthenticatedPortaalOfferteIdRoute: AuthenticatedPortaalOfferteIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DienstenRoute: DienstenRoute,
  LoginRoute: LoginRoute,
  OfferteRoute: OfferteRoute,
  OverRoute: OverRoute,
  PrivacyRoute: PrivacyRoute,
  RecentWerkRoute: RecentWerkRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RestauratieVwT2Route: RestauratieVwT2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
